from datetime import datetime
from typing import List

from sqlalchemy import Boolean, DateTime, Float, ForeignKey, Integer, String, Text
from sqlalchemy.orm import Mapped, mapped_column, relationship

from backend.core.clock import utcnow
from backend.core.database import Base


class Workout(Base):
    __tablename__ = "workouts"

    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    owner_id: Mapped[int] = mapped_column(
        ForeignKey("users.id", ondelete="CASCADE"), index=True
    )
    name: Mapped[str] = mapped_column(String(128), default="Workout")
    notes: Mapped[str | None] = mapped_column(Text, nullable=True)
    started_at: Mapped[datetime] = mapped_column(
        DateTime, default=utcnow, index=True
    )
    # Set when the workout was generated by a program session; finishing it
    # advances that program's state.
    program_id: Mapped[int | None] = mapped_column(
        ForeignKey("programs.id", ondelete="SET NULL"), nullable=True
    )
    program_lift_id: Mapped[int | None] = mapped_column(
        ForeignKey("program_lifts.id", ondelete="SET NULL"), nullable=True
    )
    finished_at: Mapped[datetime | None] = mapped_column(DateTime, nullable=True, index=True)
    # Client-generated UUID for offline-created workouts — /workouts/sync
    # upserts by (owner_id, client_id) so replaying a sync never duplicates.
    client_id: Mapped[str | None] = mapped_column(String(36), nullable=True, index=True)

    exercises: Mapped[List["WorkoutExercise"]] = relationship(
        cascade="all, delete-orphan", order_by="WorkoutExercise.position"
    )
    songs: Mapped[List["WorkoutSong"]] = relationship(
        cascade="all, delete-orphan", order_by="WorkoutSong.position"
    )


class WorkoutSong(Base):
    """One song's play window during a workout — the session soundtrack.

    Captured by the iOS companion from the system music player (the PWA can't
    see playback and never sends these). started_at is usually exact: a single
    mid-song snapshot back-computes the start from the playback position.
    ended_at is the last moment the song was observed, so it understates."""

    __tablename__ = "workout_songs"

    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    workout_id: Mapped[int] = mapped_column(
        ForeignKey("workouts.id", ondelete="CASCADE"), index=True
    )
    position: Mapped[int] = mapped_column(Integer, default=0)
    title: Mapped[str] = mapped_column(String(256))
    artist: Mapped[str | None] = mapped_column(String(256), nullable=True)
    album: Mapped[str | None] = mapped_column(String(256), nullable=True)
    # Apple Music catalog id (playbackStoreID) — stable across devices for
    # streamed tracks; null for purely local files. Aggregate by this first,
    # falling back to (title, artist).
    apple_id: Mapped[str | None] = mapped_column(String(32), nullable=True)
    # Primary genre from the iTunes catalog, backfilled server-side by
    # apple_id lookup (backend/genres.py) — the phone never sends this.
    genre: Mapped[str | None] = mapped_column(String(64), nullable=True)
    started_at: Mapped[datetime] = mapped_column(DateTime)
    ended_at: Mapped[datetime | None] = mapped_column(DateTime, nullable=True)
    # 'live' = observed by the running app; 'inferred' = reconstructed after
    # the fact (reserved for the MusicKit recently-played reconcile)
    source: Mapped[str] = mapped_column(String(12), default="live")


class WorkoutExercise(Base):
    __tablename__ = "workout_exercises"

    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    workout_id: Mapped[int] = mapped_column(
        ForeignKey("workouts.id", ondelete="CASCADE"), index=True
    )
    exercise_id: Mapped[int] = mapped_column(
        ForeignKey("exercises.id", ondelete="CASCADE"), index=True
    )
    position: Mapped[int] = mapped_column(Integer, default=0)
    rest_seconds: Mapped[int | None] = mapped_column(Integer, nullable=True)
    # Chains this exercise with the following one into a superset
    superset_with_next: Mapped[bool] = mapped_column(Boolean, default=False)
    # Copied from the template at start; suggested_weight is the progression
    # suggestion computed against the previous session
    rep_min: Mapped[int | None] = mapped_column(Integer, nullable=True)
    rep_max: Mapped[int | None] = mapped_column(Integer, nullable=True)
    suggested_weight: Mapped[float | None] = mapped_column(Float, nullable=True)
    # 'progress' (add weight) or 'deload' (back off after repeated stalls)
    suggestion_kind: Mapped[str | None] = mapped_column(String(12), nullable=True)

    sets: Mapped[List["SetEntry"]] = relationship(
        cascade="all, delete-orphan", order_by="SetEntry.position"
    )


class SetEntry(Base):
    __tablename__ = "set_entries"

    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    workout_exercise_id: Mapped[int] = mapped_column(
        ForeignKey("workout_exercises.id", ondelete="CASCADE"), index=True
    )
    position: Mapped[int] = mapped_column(Integer, default=0)
    weight: Mapped[float | None] = mapped_column(Float, nullable=True)
    reps: Mapped[int | None] = mapped_column(Integer, nullable=True)
    is_completed: Mapped[bool] = mapped_column(Boolean, default=False)
    is_warmup: Mapped[bool] = mapped_column(Boolean, default=False)
    # 'drop' | 'failure' | NULL — markers only; both still count toward stats
    set_type: Mapped[str | None] = mapped_column(String(16), nullable=True)
    is_pr: Mapped[bool] = mapped_column(Boolean, default=False)
    rpe: Mapped[float | None] = mapped_column(Float, nullable=True)
    completed_at: Mapped[datetime | None] = mapped_column(DateTime, nullable=True)
